//! Driver-agnostic query execution layer.
//!
//! [`QueryBinder`] wraps database-specific `sqlx::QueryAs` builders behind a
//! single enum, so that proc-macro-generated code never needs `#[cfg(feature)]`
//! attributes.  All driver dispatch happens inside `webr-db`.

use std::future::Future;
use std::pin::Pin;

use crate::error::DbError;
use crate::pool::DbPool;
use crate::transaction::DbTransaction;

// ═══════════════════════════════════════════════════════════════════
// Binder enums
// ═══════════════════════════════════════════════════════════════════

/// A database-agnostic query builder wrapping `sqlx::QueryAs` for the active driver.
///
/// Created by [`DbPool::query_as`] / [`DbTransaction::query_as`].
/// Chain `.bind(value)` calls to add parameters.
pub enum QueryBinder<'q, R> {
    #[cfg(feature = "postgres")]
    Postgres(sqlx::query::QueryAs<'q, sqlx::Postgres, R, sqlx::postgres::PgArguments>),
    #[cfg(feature = "mysql")]
    MySql(sqlx::query::QueryAs<'q, sqlx::MySql, R, sqlx::mysql::MySqlArguments>),
    #[cfg(feature = "sqlite")]
    Sqlite(sqlx::query::QueryAs<'q, sqlx::Sqlite, R, sqlx::sqlite::SqliteArguments<'q>>),
    #[cfg(not(any(feature = "postgres", feature = "mysql", feature = "sqlite")))]
    #[allow(unused)]
    _Phantom(std::marker::PhantomData<&'q R>),
}

/// A database-agnostic scalar query builder (for `COUNT(*)` etc.).
pub enum ScalarBinder<'q, T> {
    #[cfg(feature = "postgres")]
    Postgres(sqlx::query::QueryScalar<'q, sqlx::Postgres, T, sqlx::postgres::PgArguments>),
    #[cfg(feature = "mysql")]
    MySql(sqlx::query::QueryScalar<'q, sqlx::MySql, T, sqlx::mysql::MySqlArguments>),
    #[cfg(feature = "sqlite")]
    Sqlite(sqlx::query::QueryScalar<'q, sqlx::Sqlite, T, sqlx::sqlite::SqliteArguments<'q>>),
    #[cfg(not(any(feature = "postgres", feature = "mysql", feature = "sqlite")))]
    #[allow(unused)]
    _Phantom(std::marker::PhantomData<&'q T>),
}

/// A database-agnostic query builder for non-SELECT statements.
pub enum ExecutionBinder<'q> {
    #[cfg(feature = "postgres")]
    Postgres(sqlx::query::Query<'q, sqlx::Postgres, sqlx::postgres::PgArguments>),
    #[cfg(feature = "mysql")]
    MySql(sqlx::query::Query<'q, sqlx::MySql, sqlx::mysql::MySqlArguments>),
    #[cfg(feature = "sqlite")]
    Sqlite(sqlx::query::Query<'q, sqlx::Sqlite, sqlx::sqlite::SqliteArguments<'q>>),
    #[cfg(not(any(feature = "postgres", feature = "mysql", feature = "sqlite")))]
    #[allow(unused)]
    _Phantom(std::marker::PhantomData<&'q ()>),
}

// ═══════════════════════════════════════════════════════════════════
// Binder `bind` impls — generated by macro
// ═══════════════════════════════════════════════════════════════════

/// Generate a `bind` method for a binder with generic params `<'q, R>`.
macro_rules! __bind_qr {
    ($binder:ident, $DB:ty, $Args:ty, $variant:ident) => {
        impl<'q, R: Send + Unpin> $binder<'q, R> {
            pub fn bind<T>(self, value: T) -> Self
            where
                T: sqlx::Encode<'q, $DB> + sqlx::Type<$DB> + Send + 'q,
            {
                match self {
                    Self::$variant(q) => Self::$variant(q.bind(value)),
                    #[allow(unreachable_patterns)]
                    _ => self,
                }
            }
        }
    };
}

/// Generate a `bind` method for `ExecutionBinder` (only `<'q>`, no `R`).
macro_rules! __bind_exec {
    ($DB:ty, $Args:ty, $variant:ident) => {
        impl<'q> ExecutionBinder<'q> {
            pub fn bind<T>(self, value: T) -> Self
            where
                T: sqlx::Encode<'q, $DB> + sqlx::Type<$DB> + Send + 'q,
            {
                match self {
                    Self::$variant(q) => Self::$variant(q.bind(value)),
                    #[allow(unreachable_patterns)]
                    _ => self,
                }
            }
        }
    };
}

// QueryBinder bind — priority: pg > mysql > sqlite
#[cfg(feature = "postgres")]
__bind_qr!(QueryBinder, sqlx::Postgres, sqlx::postgres::PgArguments, Postgres);
#[cfg(all(feature = "mysql", not(feature = "postgres")))]
__bind_qr!(QueryBinder, sqlx::MySql, sqlx::mysql::MySqlArguments, MySql);
#[cfg(all(feature = "sqlite", not(feature = "postgres"), not(feature = "mysql")))]
__bind_qr!(QueryBinder, sqlx::Sqlite, sqlx::sqlite::SqliteArguments<'q>, Sqlite);

// ScalarBinder bind
#[cfg(feature = "postgres")]
__bind_qr!(ScalarBinder, sqlx::Postgres, sqlx::postgres::PgArguments, Postgres);
#[cfg(all(feature = "mysql", not(feature = "postgres")))]
__bind_qr!(ScalarBinder, sqlx::MySql, sqlx::mysql::MySqlArguments, MySql);
#[cfg(all(feature = "sqlite", not(feature = "postgres"), not(feature = "mysql")))]
__bind_qr!(ScalarBinder, sqlx::Sqlite, sqlx::sqlite::SqliteArguments<'q>, Sqlite);

// ExecutionBinder bind
#[cfg(feature = "postgres")]
__bind_exec!(sqlx::Postgres, sqlx::postgres::PgArguments, Postgres);
#[cfg(all(feature = "mysql", not(feature = "postgres")))]
__bind_exec!(sqlx::MySql, sqlx::mysql::MySqlArguments, MySql);
#[cfg(all(feature = "sqlite", not(feature = "postgres"), not(feature = "mysql")))]
__bind_exec!(sqlx::Sqlite, sqlx::sqlite::SqliteArguments<'q>, Sqlite);

// ═══════════════════════════════════════════════════════════════════
// Query-builder constructors — generated by macro
// ═══════════════════════════════════════════════════════════════════

type BoxFut<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

/// Generate `query_as`, `query_scalar`, `query_exec` methods.
///
/// Two forms:
///   pool:  `__query_buildors!(pool  { ... })` — matches on `&self.inner`
///   txn:   `__query_buildors!(driver { ... })` — matches on `self.driver()`
///
/// Each arm: `$(#[$cfg])? $pat => $Variant`
macro_rules! __query_buildors {
    (pool { $( $(#[$cfg:meta])? $pat:pat => $Variant:ident, )+ }) => {
        #[allow(unused_variables)]
        pub fn query_as<'q, R>(&'q self, sql: &'q str) -> QueryBinder<'q, R>
        where
            R: crate::Row,
        {
            match &self.inner {
                $( $(#[$cfg])? $pat => QueryBinder::$Variant(sqlx::query_as::<sqlx::$Variant, R>(sql)), )+
                #[allow(unreachable_patterns)]
                _ => unreachable!("no database feature enabled"),
            }
        }

        #[allow(unused_variables)]
        pub fn query_scalar<'q, T: crate::Scalar>(&'q self, sql: &'q str) -> ScalarBinder<'q, T> {
            match &self.inner {
                $( $(#[$cfg])? $pat => ScalarBinder::$Variant(sqlx::query_scalar::<sqlx::$Variant, T>(sql)), )+
                #[allow(unreachable_patterns)]
                _ => unreachable!("no database feature enabled"),
            }
        }

        pub fn query_exec<'q>(&'q self, sql: &'q str) -> ExecutionBinder<'q> {
            match &self.inner {
                $( $(#[$cfg])? $pat => ExecutionBinder::$Variant(sqlx::query(sql)), )+
                #[allow(unreachable_patterns)]
                _ => unreachable!("no database feature enabled"),
            }
        }
    };
    (driver { $( $(#[$cfg:meta])? $pat:pat => $Variant:ident, )+ }) => {
        #[allow(unused_variables)]
        pub fn query_as<'q, R>(&'q self, sql: &'q str) -> QueryBinder<'q, R>
        where
            R: crate::Row,
        {
            match self.driver() {
                $( $(#[$cfg])? $pat => QueryBinder::$Variant(sqlx::query_as::<sqlx::$Variant, R>(sql)), )+
                #[allow(unreachable_patterns)]
                _ => unreachable!("no database feature enabled"),
            }
        }

        #[allow(unused_variables)]
        pub fn query_scalar<'q, T: crate::Scalar>(&'q self, sql: &'q str) -> ScalarBinder<'q, T> {
            match self.driver() {
                $( $(#[$cfg])? $pat => ScalarBinder::$Variant(sqlx::query_scalar::<sqlx::$Variant, T>(sql)), )+
                #[allow(unreachable_patterns)]
                _ => unreachable!("no database feature enabled"),
            }
        }

        pub fn query_exec<'q>(&'q self, sql: &'q str) -> ExecutionBinder<'q> {
            match self.driver() {
                $( $(#[$cfg])? $pat => ExecutionBinder::$Variant(sqlx::query(sql)), )+
                #[allow(unreachable_patterns)]
                _ => unreachable!("no database feature enabled"),
            }
        }
    };
}

// ═══════════════════════════════════════════════════════════════════
// DbPool impl
// ═══════════════════════════════════════════════════════════════════

impl DbPool {
    __query_buildors! {
        pool {
            #[cfg(feature = "postgres")] crate::pool::PoolInner::Postgres(_) => Postgres,
            #[cfg(feature = "mysql")]    crate::pool::PoolInner::MySql(_)    => MySql,
            #[cfg(feature = "sqlite")]   crate::pool::PoolInner::Sqlite(_)   => Sqlite,
        }
    }

    /// Execute a query and return all rows.
    pub fn fetch_all<'q, R>(
        &'q self,
        sql: &'q str,
        build: impl FnOnce(QueryBinder<'q, R>) -> QueryBinder<'q, R> + Send + 'q,
    ) -> BoxFut<'q, Result<Vec<R>, DbError>>
    where
        R: crate::Row,
    {
        let binder = build(self.query_as(sql));
        Box::pin(async move {
            match binder {
                #[cfg(feature = "postgres")]
                QueryBinder::Postgres(q) => q.fetch_all(self.as_pg()).await.map_err(DbError::Sqlx),
                #[cfg(feature = "mysql")]
                QueryBinder::MySql(q) => q.fetch_all(self.as_my()).await.map_err(DbError::Sqlx),
                #[cfg(feature = "sqlite")]
                QueryBinder::Sqlite(q) => q.fetch_all(self.as_sq()).await.map_err(DbError::Sqlx),
                #[allow(unreachable_patterns)]
                _ => unreachable!("no database feature enabled"),
            }
        })
    }

    /// Execute a query and return an optional single row.
    pub fn fetch_optional<'q, R>(
        &'q self,
        sql: &'q str,
        build: impl FnOnce(QueryBinder<'q, R>) -> QueryBinder<'q, R> + Send + 'q,
    ) -> BoxFut<'q, Result<Option<R>, DbError>>
    where
        R: crate::Row,
    {
        let binder = build(self.query_as(sql));
        Box::pin(async move {
            match binder {
                #[cfg(feature = "postgres")]
                QueryBinder::Postgres(q) => {
                    q.fetch_optional(self.as_pg()).await.map_err(DbError::Sqlx)
                }
                #[cfg(feature = "mysql")]
                QueryBinder::MySql(q) => {
                    q.fetch_optional(self.as_my()).await.map_err(DbError::Sqlx)
                }
                #[cfg(feature = "sqlite")]
                QueryBinder::Sqlite(q) => {
                    q.fetch_optional(self.as_sq()).await.map_err(DbError::Sqlx)
                }
                #[allow(unreachable_patterns)]
                _ => unreachable!("no database feature enabled"),
            }
        })
    }

    /// Execute a query and return exactly one row.
    pub fn fetch_one<'q, R>(
        &'q self,
        sql: &'q str,
        build: impl FnOnce(QueryBinder<'q, R>) -> QueryBinder<'q, R> + Send + 'q,
    ) -> BoxFut<'q, Result<R, DbError>>
    where
        R: crate::Row,
    {
        let binder = build(self.query_as(sql));
        Box::pin(async move {
            match binder {
                #[cfg(feature = "postgres")]
                QueryBinder::Postgres(q) => q.fetch_one(self.as_pg()).await.map_err(DbError::Sqlx),
                #[cfg(feature = "mysql")]
                QueryBinder::MySql(q) => q.fetch_one(self.as_my()).await.map_err(DbError::Sqlx),
                #[cfg(feature = "sqlite")]
                QueryBinder::Sqlite(q) => q.fetch_one(self.as_sq()).await.map_err(DbError::Sqlx),
                #[allow(unreachable_patterns)]
                _ => unreachable!("no database feature enabled"),
            }
        })
    }

    /// Execute a non-SELECT statement and return the number of affected rows.
    pub fn execute<'q>(
        &'q self,
        sql: &'q str,
        build: impl FnOnce(ExecutionBinder<'q>) -> ExecutionBinder<'q> + Send + 'q,
    ) -> BoxFut<'q, Result<u64, DbError>> {
        let binder = build(self.query_exec(sql));
        Box::pin(async move {
            match binder {
                #[cfg(feature = "postgres")]
                ExecutionBinder::Postgres(q) => q
                    .execute(self.as_pg())
                    .await
                    .map(|r| r.rows_affected())
                    .map_err(DbError::Sqlx),
                #[cfg(feature = "mysql")]
                ExecutionBinder::MySql(q) => q
                    .execute(self.as_my())
                    .await
                    .map(|r| r.rows_affected())
                    .map_err(DbError::Sqlx),
                #[cfg(feature = "sqlite")]
                ExecutionBinder::Sqlite(q) => q
                    .execute(self.as_sq())
                    .await
                    .map(|r| r.rows_affected())
                    .map_err(DbError::Sqlx),
                #[allow(unreachable_patterns)]
                _ => unreachable!("no database feature enabled"),
            }
        })
    }

    /// Execute a scalar query (e.g. `SELECT COUNT(*)`) and return the value.
    pub fn fetch_scalar<'q, T>(
        &'q self,
        sql: &'q str,
        build: impl FnOnce(ScalarBinder<'q, T>) -> ScalarBinder<'q, T> + Send + 'q,
    ) -> BoxFut<'q, Result<T, DbError>>
    where
        T: crate::Scalar,
    {
        let binder = build(self.query_scalar(sql));
        Box::pin(async move {
            match binder {
                #[cfg(feature = "postgres")]
                ScalarBinder::Postgres(q) => q.fetch_one(self.as_pg()).await.map_err(DbError::Sqlx),
                #[cfg(feature = "mysql")]
                ScalarBinder::MySql(q) => q.fetch_one(self.as_my()).await.map_err(DbError::Sqlx),
                #[cfg(feature = "sqlite")]
                ScalarBinder::Sqlite(q) => q.fetch_one(self.as_sq()).await.map_err(DbError::Sqlx),
                #[allow(unreachable_patterns)]
                _ => unreachable!("no database feature enabled"),
            }
        })
    }

    /// Execute an INSERT and return the created entity.
    ///
    /// - **PostgreSQL**: uses `RETURNING` clause via `insert_sql`.
    /// - **MySQL / SQLite**: executes `insert_sql`, then fetches by
    ///   `last_insert_id` / `last_insert_rowid` via `fetch_sql`.
    pub fn insert_fetch<'q, R>(
        &'q self,
        insert_sql: &'q str,
        fetch_sql: &'q str,
        _pk_col: &'q str,
        build_insert: impl FnOnce(ExecutionBinder<'q>) -> ExecutionBinder<'q> + Send + 'q,
    ) -> BoxFut<'q, Result<R, DbError>>
    where
        R: crate::Row,
    {
        let ins = build_insert(self.query_exec(insert_sql));
        Box::pin(async move {
            match ins {
                #[cfg(feature = "postgres")]
                ExecutionBinder::Postgres(q) => {
                    q.fetch_one(self.as_pg()).await.map_err(DbError::Sqlx)
                }
                #[cfg(feature = "mysql")]
                ExecutionBinder::MySql(q) => {
                    let result = q.execute(self.as_my()).await.map_err(DbError::Sqlx)?;
                    let id = result.last_insert_id() as i64;
                    let fq = self.query_as::<R>(fetch_sql).bind(id);
                    match fq {
                        QueryBinder::MySql(q) => {
                            q.fetch_one(self.as_my()).await.map_err(DbError::Sqlx)
                        }
                        #[allow(unreachable_patterns)]
                        _ => unreachable!(),
                    }
                }
                #[cfg(feature = "sqlite")]
                ExecutionBinder::Sqlite(q) => {
                    let result = q.execute(self.as_sq()).await.map_err(DbError::Sqlx)?;
                    let id = result.last_insert_rowid();
                    let fq = self.query_as::<R>(fetch_sql).bind(id);
                    match fq {
                        QueryBinder::Sqlite(q) => {
                            q.fetch_one(self.as_sq()).await.map_err(DbError::Sqlx)
                        }
                        #[allow(unreachable_patterns)]
                        _ => unreachable!(),
                    }
                }
                #[allow(unreachable_patterns)]
                _ => unreachable!("no database feature enabled"),
            }
        })
    }
}

// ═══════════════════════════════════════════════════════════════════
// DbTransaction impl
// ═══════════════════════════════════════════════════════════════════

impl DbTransaction {
    __query_buildors! {
        driver {
            #[cfg(feature = "postgres")] crate::pool::Driver::Postgres => Postgres,
            #[cfg(feature = "mysql")]    crate::pool::Driver::MySql    => MySql,
            #[cfg(feature = "sqlite")]   crate::pool::Driver::Sqlite   => Sqlite,
        }
    }

    /// Execute a query and return all rows (transaction context).
    pub fn fetch_all<'q, R>(
        &'q self,
        sql: &'q str,
        build: impl FnOnce(QueryBinder<'q, R>) -> QueryBinder<'q, R> + Send + 'q,
    ) -> BoxFut<'q, Result<Vec<R>, DbError>>
    where
        R: crate::Row,
    {
        let binder = build(self.query_as(sql));
        Box::pin(async move {
            let mut __g = self.lock().await;
            match binder {
                #[cfg(feature = "postgres")]
                QueryBinder::Postgres(q) => q
                    .fetch_all(Self::as_pg(&mut __g))
                    .await
                    .map_err(DbError::Sqlx),
                #[cfg(feature = "mysql")]
                QueryBinder::MySql(q) => q
                    .fetch_all(Self::as_my(&mut __g))
                    .await
                    .map_err(DbError::Sqlx),
                #[cfg(feature = "sqlite")]
                QueryBinder::Sqlite(q) => q
                    .fetch_all(Self::as_sq(&mut __g))
                    .await
                    .map_err(DbError::Sqlx),
                #[allow(unreachable_patterns)]
                _ => unreachable!("no database feature enabled"),
            }
        })
    }

    /// Execute a query and return an optional single row (transaction context).
    pub fn fetch_optional<'q, R>(
        &'q self,
        sql: &'q str,
        build: impl FnOnce(QueryBinder<'q, R>) -> QueryBinder<'q, R> + Send + 'q,
    ) -> BoxFut<'q, Result<Option<R>, DbError>>
    where
        R: crate::Row,
    {
        let binder = build(self.query_as(sql));
        Box::pin(async move {
            let mut __g = self.lock().await;
            match binder {
                #[cfg(feature = "postgres")]
                QueryBinder::Postgres(q) => q
                    .fetch_optional(Self::as_pg(&mut __g))
                    .await
                    .map_err(DbError::Sqlx),
                #[cfg(feature = "mysql")]
                QueryBinder::MySql(q) => q
                    .fetch_optional(Self::as_my(&mut __g))
                    .await
                    .map_err(DbError::Sqlx),
                #[cfg(feature = "sqlite")]
                QueryBinder::Sqlite(q) => q
                    .fetch_optional(Self::as_sq(&mut __g))
                    .await
                    .map_err(DbError::Sqlx),
                #[allow(unreachable_patterns)]
                _ => unreachable!("no database feature enabled"),
            }
        })
    }

    /// Execute a query and return exactly one row (transaction context).
    pub fn fetch_one<'q, R>(
        &'q self,
        sql: &'q str,
        build: impl FnOnce(QueryBinder<'q, R>) -> QueryBinder<'q, R> + Send + 'q,
    ) -> BoxFut<'q, Result<R, DbError>>
    where
        R: crate::Row,
    {
        let binder = build(self.query_as(sql));
        Box::pin(async move {
            let mut __g = self.lock().await;
            match binder {
                #[cfg(feature = "postgres")]
                QueryBinder::Postgres(q) => q
                    .fetch_one(Self::as_pg(&mut __g))
                    .await
                    .map_err(DbError::Sqlx),
                #[cfg(feature = "mysql")]
                QueryBinder::MySql(q) => q
                    .fetch_one(Self::as_my(&mut __g))
                    .await
                    .map_err(DbError::Sqlx),
                #[cfg(feature = "sqlite")]
                QueryBinder::Sqlite(q) => q
                    .fetch_one(Self::as_sq(&mut __g))
                    .await
                    .map_err(DbError::Sqlx),
                #[allow(unreachable_patterns)]
                _ => unreachable!("no database feature enabled"),
            }
        })
    }

    /// Execute a non-SELECT statement and return affected rows (transaction context).
    pub fn execute<'q>(
        &'q self,
        sql: &'q str,
        build: impl FnOnce(ExecutionBinder<'q>) -> ExecutionBinder<'q> + Send + 'q,
    ) -> BoxFut<'q, Result<u64, DbError>> {
        let binder = build(self.query_exec(sql));
        Box::pin(async move {
            let mut __g = self.lock().await;
            match binder {
                #[cfg(feature = "postgres")]
                ExecutionBinder::Postgres(q) => q
                    .execute(Self::as_pg(&mut __g))
                    .await
                    .map(|r| r.rows_affected())
                    .map_err(DbError::Sqlx),
                #[cfg(feature = "mysql")]
                ExecutionBinder::MySql(q) => q
                    .execute(Self::as_my(&mut __g))
                    .await
                    .map(|r| r.rows_affected())
                    .map_err(DbError::Sqlx),
                #[cfg(feature = "sqlite")]
                ExecutionBinder::Sqlite(q) => q
                    .execute(Self::as_sq(&mut __g))
                    .await
                    .map(|r| r.rows_affected())
                    .map_err(DbError::Sqlx),
                #[allow(unreachable_patterns)]
                _ => unreachable!("no database feature enabled"),
            }
        })
    }

    /// Execute a scalar query (transaction context).
    pub fn fetch_scalar<'q, T>(
        &'q self,
        sql: &'q str,
        build: impl FnOnce(ScalarBinder<'q, T>) -> ScalarBinder<'q, T> + Send + 'q,
    ) -> BoxFut<'q, Result<T, DbError>>
    where
        T: crate::Scalar,
    {
        let binder = build(self.query_scalar(sql));
        Box::pin(async move {
            let mut __g = self.lock().await;
            match binder {
                #[cfg(feature = "postgres")]
                ScalarBinder::Postgres(q) => q
                    .fetch_one(Self::as_pg(&mut __g))
                    .await
                    .map_err(DbError::Sqlx),
                #[cfg(feature = "mysql")]
                ScalarBinder::MySql(q) => q
                    .fetch_one(Self::as_my(&mut __g))
                    .await
                    .map_err(DbError::Sqlx),
                #[cfg(feature = "sqlite")]
                ScalarBinder::Sqlite(q) => q
                    .fetch_one(Self::as_sq(&mut __g))
                    .await
                    .map_err(DbError::Sqlx),
                #[allow(unreachable_patterns)]
                _ => unreachable!("no database feature enabled"),
            }
        })
    }

    /// Execute an INSERT and return the created entity (transaction context).
    pub fn insert_fetch<'q, R>(
        &'q self,
        insert_sql: &'q str,
        fetch_sql: &'q str,
        _pk_col: &'q str,
        build_insert: impl FnOnce(ExecutionBinder<'q>) -> ExecutionBinder<'q> + Send + 'q,
    ) -> BoxFut<'q, Result<R, DbError>>
    where
        R: crate::Row,
    {
        let ins = build_insert(self.query_exec(insert_sql));
        Box::pin(async move {
            let mut __g = self.lock().await;
            match ins {
                #[cfg(feature = "postgres")]
                ExecutionBinder::Postgres(q) => q
                    .fetch_one(Self::as_pg(&mut __g))
                    .await
                    .map_err(DbError::Sqlx),
                #[cfg(feature = "mysql")]
                ExecutionBinder::MySql(q) => {
                    let result = q
                        .execute(Self::as_my(&mut __g))
                        .await
                        .map_err(DbError::Sqlx)?;
                    let id = result.last_insert_id() as i64;
                    let fq = self.query_as::<R>(fetch_sql).bind(id);
                    match fq {
                        QueryBinder::MySql(q) => q
                            .fetch_one(Self::as_my(&mut __g))
                            .await
                            .map_err(DbError::Sqlx),
                        #[allow(unreachable_patterns)]
                        _ => unreachable!(),
                    }
                }
                #[cfg(feature = "sqlite")]
                ExecutionBinder::Sqlite(q) => {
                    let result = q
                        .execute(Self::as_sq(&mut __g))
                        .await
                        .map_err(DbError::Sqlx)?;
                    let id = result.last_insert_rowid();
                    let fq = self.query_as::<R>(fetch_sql).bind(id);
                    match fq {
                        QueryBinder::Sqlite(q) => q
                            .fetch_one(Self::as_sq(&mut __g))
                            .await
                            .map_err(DbError::Sqlx),
                        #[allow(unreachable_patterns)]
                        _ => unreachable!(),
                    }
                }
                #[allow(unreachable_patterns)]
                _ => unreachable!("no database feature enabled"),
            }
        })
    }
}
