[book]
title = "WebR 框架文档"
authors = ["wxg"]
language = "zh"
src = "."

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/xgpxg/webr"
edit-url-template = "https://github.com/xgpxg/webr/edit/main/docs/{path}"
