use webr::prelude::*;
use webr::{FileResponse, Error};

// ─── 文件上传 Controller ──────────────────────────────────

#[controller]
pub struct FileController;

#[controller]
impl FileController {
    #[get("/")]
    async fn index(&self) -> &'static str {
        "File Upload/Download Example\n\
         - POST /upload: multipart/form-data upload\n\
         - GET  /download: download generated bytes\n\
         - GET  /download/{filename}: download file by name\n\
         - GET  /preview: inline display (image)"
    }
    /// 文件上传（支持附带普通参数）
    /// 用 `field.file_name()` 区分文件字段和普通文本字段
    #[post("/upload")]
    async fn upload(&self, mut multipart: webr::Multipart) -> webr::Json<serde_json::Value> {
        let mut files = Vec::new();
        let mut params = serde_json::Map::new();

        while let Some(field) = multipart.next_field().await.unwrap() {
            if let Some(filename) = field.file_name().map(|s| s.to_string()) {
                // 文件字段
                let content_type = field.content_type().unwrap_or("unknown").to_string();
                let data = field.bytes().await.unwrap();
                files.push(serde_json::json!({
                    "name": filename,
                    "content_type": content_type,
                    "size": data.len()
                }));
            } else {
                // 普通文本字段（如 description、tags 等）
                let key = field.name().unwrap_or("unknown").to_string();
                let value = field.text().await.unwrap();
                params.insert(key, serde_json::Value::String(value));
            }
        }

        webr::Json(serde_json::json!({
            "uploaded": files.len(),
            "files": files,
            "params": params
        }))
    }

    /// 从内存字节生成文件下载
    #[get("/download")]
    async fn download_bytes(&self) -> FileResponse {
        let content = "Hello, this is a generated file!\nLine 2\nLine 3";
        FileResponse::bytes(content.as_bytes().to_vec(), "hello.txt")
    }

    /// 从文件路径下载（自动推断 MIME 类型）
    /// 文件不存在时返回 404
    #[get("/download/{filename}")]
    async fn download_file(&self, path: webr::Path<(String,)>) -> std::result::Result<FileResponse, Error> {
        let filename = &path.0 .0;
        // 示例目录：当前工作目录下的 downloads 文件夹
        let file_path = format!("downloads/{}", filename);
        FileResponse::from_path(file_path).await
    }

    /// 内联展示图片（浏览器直接展示，不触发下载）
    #[get("/preview")]
    async fn preview(&self) -> FileResponse {
        // 生成一个 1x1 像素的透明 PNG
        let png_bytes: Vec<u8> = vec![
            0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D, 0x49, 0x48,
            0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x06, 0x00, 0x00,
            0x00, 0x1F, 0x15, 0xC4, 0x89, 0x00, 0x00, 0x00, 0x0D, 0x49, 0x44, 0x41, 0x54, 0x78,
            0x9C, 0x63, 0x00, 0x01, 0x00, 0x00, 0x05, 0x00, 0x01, 0x0D, 0x0A, 0x2D, 0xB4, 0x00,
            0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82,
        ];
        FileResponse::bytes(png_bytes, "preview.png").inline()
    }
}

// ─── 启动入口 ──────────────────────────────────────────

#[webr::main]
async fn main(app: &mut webr::AppBuilder) -> std::result::Result<(), Error> {
    // 增大请求体限制以支持文件上传（默认 2MB，这里设为 50MB）
    app.unified_response();
    Ok(())
}
